export const PLACES_LIST_REQUEST = "PLACES_LIST_REQUEST";
export const PLACES_LIST_SUCCESS = "PLACES_LIST_SUCCESS";
export const PLACES_LIST_FAIL = "PLACES_LIST_FAIL";

export const PLACE_DETAILS_REQUEST = "PLACE_DETAILS_REQUEST";
export const PLACE_DETAILS_SUCCESS = "PLACE_DETAILS_SUCCESS";
export const PLACE_DETAILS_FAIL = "PLACE_DETAILS_FAIL";

export const PLACE_CREATE_REQUEST = "PLACE_CREATE_REQUEST";
export const PLACE_CREATE_SUCCESS = "PLACE_CREATE_SUCCESS";
export const PLACE_CREATE_FAIL = "PLACE_CREATE_FAIL";

export const PLACE_DELETE_REQUEST = "PLACE_DELETE_REQUEST";
export const PLACE_DELETE_SUCCESS = "PLACE_DELETE_SUCCESS";
export const PLACE_DELETE_FAIL = "PLACE_DELETE_FAIL";
